name: CI Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          echo "=== Система ==="
          uname -a
          echo "=== Текущая папка ==="
          pwd
          echo "=== Что внутри ==="
          ls -la

      - name: Python version
        run: python3 --version

      - name: Create test file
        run: echo "✅ CI/CD работает!" > result.txt

      - name: Read test file
        run: cat result.txt
